services:
  db:
    container_name: "db_postgres"
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boty-db
    ports:
      - "5433:5432"

volumes:
  db_data:
