test_data = [
    ("Cześć, jak się masz?", "Hi, how are you?"),
    ("Kocham programowanie.", "I love coding."),
    ("Jak masz na imię?", "What is your name?"),
    ("Ile to kosztuje?", "How much does it cost?"),
    ("Gdzie jest najbliższy bank?", "Where is the nearest bank?"),
    ("Czy możesz mi pomóc, proszę?", "Can you help me, please?"),
    ("To jest piękny dzień.", "This is a beautiful day."),
    ("Chcę iść do parku.", "I want to go to the park."),
    ("Czy mówisz po angielsku?", "Do you speak English?"),
    ("Która jest godzina?", "What time is it?"),
    ("Gdzie jest toaleta?", "Where is the restroom?"),
    ("Potrzebuję pomocy.", "I need some help."),
    ("Jestem głodny.", "I am hungry."),
    ("Jestem spragniony.", "I am thirsty."),
    ("Jestem zmęczony.", "I am tired."),
    ("Jedzenie jest pyszne.", "The food is delicious."),
    ("Mam pytanie.", "I have a question."),
    ("Przepraszam.", "I'm sorry."),
    ("Nie rozumiem.", "I don't understand."),
    ("Dziękuję bardzo.", "Thank you very much."),
    ("Nie ma za co.", "You're welcome."),
    ("Jak się czujesz?", "How are you feeling?"),
    ("Jaka jest dzisiaj pogoda?", "What's the weather like today?"),
    ("Idę do kina.", "I'm going to the movies."),
    ("Gdzie jest dworzec kolejowy?", "Where is the train station?"),
    ("Zgubiłem się.", "I'm lost."),
    ("Jaki jest twój ulubiony kolor?", "What's your favorite color?"),
    ("Jestem z Polski.", "I'm from Poland."),
    ("Czy masz rezerwację?", "Do you have a reservation?"),
    ("Co jest na menu?", "What's on the menu?"),
    ("Jak powiedzieć 'cześć' po angielsku?", "How do you say 'hello' in English?"),
    ("Potrzebuję lekarza.", "I need a doctor."),
    ("Jestem uczulony na orzeszki ziemne.", "I'm allergic to peanuts."),
    ("Czy mogę prosić o rachunek?", "Can I have the bill, please?"),
    ("Gdzie jest najbliższy szpital?", "Where is the nearest hospital?"),
    ("Jakie jest twoje ulubione jedzenie?", "What's your favorite food?"),
    ("Ile trwa dojazd tam?", "How long does it take to get there?"),
    ("Jaki jest twój numer telefonu?", "What's your phone number?"),
    ("Idę na plażę.", "I'm going to the beach."),
    ("Jestem uczulony na owoce morza.", "I'm allergic to shellfish."),
    ("Jestem uczulony na gluten.", "I'm allergic to gluten."),
    ("Muszę kupić trochę zakupów spożywczych.", "I need to buy some groceries."),
    ("Jaki jest hasło do WiFi?", "What's the WiFi password?"),
    ("Czy masz mapę?", "Do you have a map?"),
    ("Nie mam gotówki.", "I don't have any cash."),
    ("Czy jest w pobliżu apteka?", "Is there a pharmacy nearby?"),
    ("Idę do muzeum.", "I'm going to the museum.")
]
