alter table if exists chats drop constraint if exists FKch66t7thbwgcl2j3ypqvch13f;
alter table if exists chat_users drop constraint if exists FKchyf3h9uvw98r0hv6t5850q1n;
alter table if exists message drop constraint if exists FKd6e08bb9nhj992kma0r6777dq;
alter table if exists user_chat_mapping drop constraint if exists FKtqme8fwdw2nq4nquttifiwla1;
alter table if exists user_chat_mapping drop constraint if exists FKmi4lkpqosu56xe75fku0pudf0;
alter table if exists user_group_mapping drop constraint if exists FKa88e1jtjkeq9io2dc9gvvy0d0;
alter table if exists user_group_mapping drop constraint if exists FKfvjyay0dkbjlveggjy3dmapyr;
alter table if exists user_group_mapping drop constraint if exists FKix6687ioyf3x35ovwoswh2h7a;
drop table if exists chats cascade;
drop table if exists chat_users cascade;
drop table if exists groups cascade;
drop table if exists message cascade;
drop table if exists roles cascade;
drop table if exists user_chat_mapping cascade;
drop table if exists user_group_mapping cascade;
drop table if exists user cascade;
