alter table if exists "chat" drop constraint if exists FKf7mvimui7xb2en91g8l2cc7bg;
alter table if exists "chat" drop constraint if exists FKfm2ua90l3o72k08klruxx4ae4;
alter table if exists group_chat_mapping drop constraint if exists FK9o0x41k7qj14cmrvie53ycxj8;
alter table if exists group_chat_mapping drop constraint if exists FKj7c7ly99y5ippylrsp066jxhm;
alter table if exists group_announcement drop constraint if exists FKc2f2ojc192d8f3e5ixxpjr5jm;
alter table if exists invitation_token drop constraint if exists FK5n8pdi2u9spjrs539kksq0s51;
alter table if exists message drop constraint if exists FK7c357n8lrich8wher368e0tsf;
alter table if exists user_group drop constraint if exists FK71ue7uuqo0neoodkx7smf7e3o;
alter table if exists user_group drop constraint if exists FK1vm7hjlu1n79o7y4ga4091dj6;
alter table if exists user_roles drop constraint if exists FK5oliy2kvoc4yf2c4s5h67m7pq;
alter table if exists user_roles drop constraint if exists FK7ivp84f52aa3vd7ndq0oh0279;
alter table if exists user_group_role drop constraint if exists FKci8gnvkfesk10k58on4f3lofm;
alter table if exists user_group_role drop constraint if exists FKka4vueh9c5d8n1pbditov3r59;
alter table if exists user_group_role drop constraint if exists FK9sfxyaxy37gpn0s0jfumfxhk6;
drop table if exists "chat" cascade;
drop table if exists "group" cascade;
drop table if exists "role" cascade;
drop table if exists "user" cascade;
drop table if exists chat_platform cascade;
drop table if exists group_chat_mapping cascade;
drop table if exists group_announcement cascade;
drop table if exists invitation_token cascade;
drop table if exists message cascade;
drop table if exists user_group cascade;
drop table if exists user_roles cascade;
drop table if exists user_group_role cascade;
