alter table if exists "chat" drop constraint if exists FK3n2dvjw1q18aw8bm8w0nkot5j;
alter table if exists "file" drop constraint if exists FKriju12iqu9fhayhwbwc2m3be4;
alter table if exists group_chat_mapping drop constraint if exists FK9o0x41k7qj14cmrvie53ycxj8;
alter table if exists group_chat_mapping drop constraint if exists FKj7c7ly99y5ippylrsp066jxhm;
alter table if exists group_announcement drop constraint if exists FKc2f2ojc192d8f3e5ixxpjr5jm;
alter table if exists invitation_token drop constraint if exists FK5n8pdi2u9spjrs539kksq0s51;
alter table if exists message drop constraint if exists FKg9vt0r6ilcsvkne8xlkpu4i76;
alter table if exists user_group drop constraint if exists FK1vm7hjlu1n79o7y4ga4091dj6;
alter table if exists user_group drop constraint if exists FK71ue7uuqo0neoodkx7smf7e3o;
alter table if exists user_group_role drop constraint if exists FKci8gnvkfesk10k58on4f3lofm;
alter table if exists user_group_role drop constraint if exists FKka4vueh9c5d8n1pbditov3r59;
alter table if exists user_group_role drop constraint if exists FK9sfxyaxy37gpn0s0jfumfxhk6;
alter table if exists users_role drop constraint if exists FKoy0ltcxpfkatmbrql5t54p5un;
alter table if exists users_role drop constraint if exists FKego7uq09gdp3tkt4eknvjgwf2;
drop table if exists "chat" cascade;
drop table if exists "file" cascade;
drop table if exists "group" cascade;
drop table if exists "role" cascade;
drop table if exists "user" cascade;
drop table if exists chatplatform cascade;
drop table if exists group_chat_mapping cascade;
drop table if exists group_announcement cascade;
drop table if exists invitation_token cascade;
drop table if exists message cascade;
drop table if exists user_group cascade;
drop table if exists user_group_role cascade;
drop table if exists users_role cascade;
alter table if exists "chat" drop constraint if exists FK3n2dvjw1q18aw8bm8w0nkot5j;
alter table if exists "file" drop constraint if exists FKriju12iqu9fhayhwbwc2m3be4;
alter table if exists group_chat_mapping drop constraint if exists FK9o0x41k7qj14cmrvie53ycxj8;
alter table if exists group_chat_mapping drop constraint if exists FKj7c7ly99y5ippylrsp066jxhm;
alter table if exists group_announcement drop constraint if exists FKc2f2ojc192d8f3e5ixxpjr5jm;
alter table if exists invitation_token drop constraint if exists FK5n8pdi2u9spjrs539kksq0s51;
alter table if exists message drop constraint if exists FKg9vt0r6ilcsvkne8xlkpu4i76;
alter table if exists user_group drop constraint if exists FK1vm7hjlu1n79o7y4ga4091dj6;
alter table if exists user_group drop constraint if exists FK71ue7uuqo0neoodkx7smf7e3o;
alter table if exists user_group_role drop constraint if exists FKci8gnvkfesk10k58on4f3lofm;
alter table if exists user_group_role drop constraint if exists FKka4vueh9c5d8n1pbditov3r59;
alter table if exists user_group_role drop constraint if exists FK9sfxyaxy37gpn0s0jfumfxhk6;
alter table if exists users_role drop constraint if exists FKoy0ltcxpfkatmbrql5t54p5un;
alter table if exists users_role drop constraint if exists FKego7uq09gdp3tkt4eknvjgwf2;
drop table if exists "chat" cascade;
drop table if exists "file" cascade;
drop table if exists "group" cascade;
drop table if exists "role" cascade;
drop table if exists "user" cascade;
drop table if exists chatplatform cascade;
drop table if exists group_chat_mapping cascade;
drop table if exists group_announcement cascade;
drop table if exists invitation_token cascade;
drop table if exists message cascade;
drop table if exists user_group cascade;
drop table if exists user_group_role cascade;
drop table if exists users_role cascade;
