# Generated by Django 5.1.4 on 2024-12-10 00:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_group_created_at_remove_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
